version: 1.0.{build}

image: Visual Studio 2022

environment:
  PYTHON: C:\Python312-x64

init:
  - ps: $env:PATH = "$env:PYTHON;$env:PYTHON\Scripts;$env:PATH"
  - python --version

install:
  - ps: choco install innosetup -y

build_script:
  - ps: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
  - ps: .\build_windows.ps1
  - ps: .\inno_build.ps1 -SkipBuild
  - ps: Compress-Archive -Path dist\smtp_unlock -DestinationPath SMTP_Unlock_App_Folder.zip -Force

artifacts:
  - path: installer\SMTP_Unlock_Setup.exe
    name: SMTP_Unlock_Setup
  - path: SMTP_Unlock_App_Folder.zip
    name: SMTP_Unlock_App_Folder
